// <auto-generated />
using System;
using CardPaymentServiceAPI.DatabaseConnection.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardPaymentServiceAPI.DatabaseConnection.Migrations
{
    [DbContext(typeof(CardPaymentServiceDbContext))]
    partial class CardPaymentServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardPaymentServiceAPI.Models.CardsDetails", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountLinkedToCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardExpiry")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EncryptedCVV")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EncryptedCardPan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("ReoccuringPaymentEnabled")
                        .HasColumnType("bit");

                    b.HasKey("CardId");

                    b.ToTable("CardsDetails");
                });

            modelBuilder.Entity("CardPaymentServiceAPI.Models.Fintechs", b =>
                {
                    b.Property<int>("FintechID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreationReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FintechEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FintechName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("FintechID");

                    b.ToTable("Fintechs");
                });

            modelBuilder.Entity("CardPaymentServiceAPI.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EncryptedCardPan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FintechID")
                        .HasColumnType("int");

                    b.Property<string>("FintechName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaymentSuccessful")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReocurringPayment")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentResponseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReoccuringPaymentId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("FintechID");

                    b.HasIndex("ReoccuringPaymentId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("CardPaymentServiceAPI.Models.ReoccuringPayment", b =>
                {
                    b.Property<int>("ReoccuringPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentPayementResponseMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentPaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CurrentPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentPaymentResponseCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CurrentPaymentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("EncryptedCardPan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("FintechsFintechID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextPayemntDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReoccuringPaymentFrquencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReoccuringPaymentFrquencyIdReoccuringPaymentFrequencyId")
                        .HasColumnType("int");

                    b.Property<bool>("ReoccuringPaymentStatus")
                        .HasColumnType("bit");

                    b.HasKey("ReoccuringPaymentId");

                    b.HasIndex("CardId");

                    b.HasIndex("FintechsFintechID");

                    b.HasIndex("ReoccuringPaymentFrquencyIdReoccuringPaymentFrequencyId");

                    b.ToTable("ReoccuringPayment");
                });

            modelBuilder.Entity("CardPaymentServiceAPI.Models.ReoccuringPaymentFrquency", b =>
                {
                    b.Property<int>("ReoccuringPaymentFrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReoccuringPaymentFrequencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReoccuringPaymentFrequencyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReoccuringPaymentFrequencyId");

                    b.ToTable("ReoccuringPaymentFrquency");
                });

            modelBuilder.Entity("CardPaymentServiceAPI.Models.Payment", b =>
                {
                    b.HasOne("CardPaymentServiceAPI.Models.Fintechs", "Fintech")
                        .WithMany()
                        .HasForeignKey("FintechID");

                    b.HasOne("CardPaymentServiceAPI.Models.ReoccuringPayment", "ReoccuringPayment")
                        .WithMany()
                        .HasForeignKey("ReoccuringPaymentId");

                    b.Navigation("Fintech");

                    b.Navigation("ReoccuringPayment");
                });

            modelBuilder.Entity("CardPaymentServiceAPI.Models.ReoccuringPayment", b =>
                {
                    b.HasOne("CardPaymentServiceAPI.Models.CardsDetails", "Card")
                        .WithMany()
                        .HasForeignKey("CardId");

                    b.HasOne("CardPaymentServiceAPI.Models.Fintechs", "Fintechs")
                        .WithMany()
                        .HasForeignKey("FintechsFintechID");

                    b.HasOne("CardPaymentServiceAPI.Models.ReoccuringPaymentFrquency", "ReoccuringPaymentFrquencyId")
                        .WithMany()
                        .HasForeignKey("ReoccuringPaymentFrquencyIdReoccuringPaymentFrequencyId");

                    b.Navigation("Card");

                    b.Navigation("Fintechs");

                    b.Navigation("ReoccuringPaymentFrquencyId");
                });
#pragma warning restore 612, 618
        }
    }
}
